# Generated by Django 3.2.9 on 2021-12-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_not_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_total',
            field=models.IntegerField(),
        ),
    ]
