# Generated by Django 3.2.5 on 2021-11-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_not_available',
        ),
    ]
