# Generated by Django 3.2.5 on 2021-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinha', '0002_remove_inventory_item_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_not_available',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
