# Generated by Django 3.2.5 on 2021-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinha', '0003_inventory_item_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='location',
        ),
    ]
